#!/bin/sh
 
    set -e
 
    case "$1" in
    configure)
    update-alternatives --remove   bin2c /usr/bin/bin2c.winexe
    update-alternatives --install /usr/bin/bin2c bin2c /usr/bin/bin2c.winexe 60
    ;;
    esac
