#!/bin/bash


# Some important configuration:'

workingdir=~/WorkingCopy-$2
workpath=$workingdir/$2
mountdir="/mnt/AndroidImageMount"


#zenity --info --text "Mount android ext4 immage in progress" --title "In-Progress"

error=0
 
if ! [ -e "$1" ]; then
	echo -e -n  "android image file does not exist.\n"
	error=1
fi

#assign a free loop device
loopdevice=$( losetup -f )
if ! [ -z "$loopdevice" ]; then
	echo -e -n  "no free loop devices exist, plese free one up !\n"
	error=1
fi
 
#other checks

#check for previous working copy
if [ -d "$workingdir" ]; then
	echo -e -n  "$workingdir already exists q to quit or any other key to write over\n"
	read -s -n1 _AXE_TMP_CHAR
	if [[ $_AXE_TMP_CHAR == "q" ]]; then
		error=1
	else
		rm -fr $workingdir
	fi
fi



 
 if [[ $error == 1 ]]; then
  echo -e -n  "press any key to quit"
  read -s -n1 _AXE_TMP_CHAR
  exit 1
 fi

 echo -e -n "extract image $1 to $workpath \n"
 mkdir $workingdir
 simg2img $1 $workpath
#check exit status of sim2img for correct extract

# check temp image there

if ! [ -e "$workpath" ]; then
	echo -e -n  "simg2img refused to extract the file check the output.\n"
	echo -e -n  "press any key to quit"
	read -s -n1 _AXE_TMP_CHAR
	exit 1
fi


echo -e -n "Mounting android image $workpath to $mountdir using loopdevice $loopdevice \n"
losetup $loopdevice $workpath

echo -e -n  "Done! Press S to save working copy back to $1 or any other key just to unmount and clen up \n"
read -s -n1 _AXE_TMP_CHAR
if [[ $_AXE_TMP_CHAR == "s" ]]; then
 
	losetup -d $loopdevice
	img2simg $workpath $1
	rm -fr $workingdir
 
else
	losetup -d $loopdevice
	rm -fr $workingdir
fi
 

exit 0





