#!/bin/bash
# example file to be used with --hookdir
#
#create $TMP and $TMPDIR
[ -n "$TMP" -a ! -d "$TMP" ] && mkdir -p "$TMP" || true
[ -n "$TMPDIR" -a ! -d "$TMPDIR" ] && mkdir -p "$TMPDIR" || true


