#!/bin/bash

function GetRelease()
{

	#first argument dl link
		#xxxxxx ...variable name name
release_version=$(curl -s https://github.com/linuxmint/$1/releases | grep -m 3 "/linuxmint/$1/archive/" | sed 's/.*.zip"//' | sed -n 's/.*\///p' | sed 's/".*//')
Info " i made thew relese version as $release_version"
		
aaa_escape=0
while [[ $aaa_escape -eq 0 ]]; do
	wget "https://github.com/linuxmint/Cinnamon/archive/$release_version"
	if [[ ! $? -eq 0 ]]; then
		Warn "failed to download the release version of $1"
		Warn "since with this build i cant miss this download i need to try again"
		Warn "or it could be down to the webpage formate changing"
		Warn "if thats not good for you ${aaa_ctrl_c} to quit"
		AnyKey
	else
		tar -xzf $1*.tar.gz
		aaa_escape=1
	fi
done

}

GetRelease nemo
