#!/bin/bash


################ common header identical except for usage, getopts etc #########################################################################################################
shopt -s extglob


bdate=$(date +%Y%m%d-%H%M%S)

Usage() {
  cat <<EOF
usage: ${0##*/}


EOF
}

if [[ $1 = @(-h|--help) ]]; then
  Usage
  exit 1
fi

#source common functions
if [[ -r /usr/bin/aaa-common-functions ]]; then
	. /usr/bin/aaa-common-functions
	if [[ ! $? -eq 0 ]]; then
		echo " failed to source common functions at /usr/bin/aaa-common-functions"
		echo "quitting !! "
	fi
else
	echo " failed to find common functions at /usr/bin/aaa-common-functions"
	echo "setting up common aaa environment"
	echo "quitting !! "
fi


#source config
if [ -r /usr/share/aaa/aaa-master-config ]; then
  Info "found my master config file.. reading it"
  . /usr/share/aaa/aaa-master-config
	if [ -r $HOME/.aaa-local-config ]; then
		Info "found a local settings file.. reading it"
		. $HOME/.aaa-local-config
	fi
else
	Fuck "Failed to find master settings file quitting"
	exit 1
fi


mod_file_list="libgnome2-0 gnome-applets"


#setup working dir

CleanMyBuildArea
MakeADir "$aaa_pupvm_cache_dir/$aaa_debian_distro/$bdate"

cd "$aaa_work_dir"


for pkg_working in $mod_file_list ; do
	apt-get download $pkg_working
	pkg_name=$(find . -maxdepth 1 -mindepth 1 -type f)
	ProcessBeb $aaa_work_dir ${pkg_name#./}
	dpkg -i ${pkg_name#./}
	find . -maxdepth 1 -mindepth 1 -type f -exec mv -f '{}' "$aaa_pupvm_cache_dir/$aaa_debian_distro/$bdate" \;
done










