#!/bin/bash

#
# ##################################################################
#
#

cd "$HOME"

Usage() {
  cat <<EOF
usage: aaa-setup-tmpfs

  Currently this script takes no
  options or arguments, when called it
  will setup a custom tmpfs dir at 
  $aaa_tmpfs_location
  the size can be configured in 
  /usr/share/aaa/aaa-master-config
  It will also setup your personal
  gpg key for auto package signing
  if you desire

EOF
}


if [[ $1 = @(-h|--help) ]]; then
  Usage
  exit 1
fi

#source common functions
if [[ -r /usr/bin/aaa-common-functions ]]; then
	. /usr/bin/aaa-common-functions
	if [[ ! $? -eq 0 ]]; then
		echo " failed to source common functions at /usr/bin/aaa-common-functions"
		echo "quitting !! "
		exit 1
	fi
else
	echo " failed to find common functions at /usr/bin/aaa-common-functions"
	echo "quitting !! "
	exit 1
fi

#source settings
if [ -r $HOME/.aaa_settings ]; then
  Info "found a settings file.. reading it"
  . $HOME/.aaa_settings
fi

export AAA_DEBIAN_DISTRO=""
export AAA_SUPRESS_LOCAL_PBUILDERRC="yes"


#source config
if [[ -e /usr/share/aaa/aaa-master-config ]]; then
  Info "found my master config file.. reading it"
	. /usr/share/aaa/aaa-master-config
	if [[ -e $HOME/.aaa-local-config ]]; then
		Info "[aaa-setup-pbuilder]found a local  config file.. reading it"
		. $HOME/.aaa-local-config
	fi
else
	Fuck "Failed to find master config file quitting"
fi


#check script dependencies
CheckMyDeps "reprepro pbuilder cat grep"


Block "setup gpg key"
if [[ ! -e "$HOME/.gnupg/trustedkeys.gpg" ]]; then
	Info "$HOME/.gnupg/trustedkeys.gpg does not exist"
	Info "do you wana generate a new gpg key ?"
	Info "or export you existing keys to $HOME/.gnupg/trustedkeys.gpg"
	MenuActive "y" "to use the command line util to gen a gpg key"
	MenuActive "n" "to skip generation and use a existing gpg key"
	MenuActive "i" "to download and install your needed gpg components"
	MenuActive "any other key" "to skip this altogether"
	read -s -n1 aaa_tmpchr
	case $aaa_tmpchr in
			y) # generate gpg-key
				gpg --gen-key 
				gpg --export -o "$HOME/.gnupg/trustedkeys.gpg" ;;
			n) Info "skipping gpg key generation, exporting" 
			gpg --export -o "$HOME/.gnupg/trustedkeys.gpg" ;;
	
			*) Info "skipping gpg key generation, skipping key export" ;;
	esac
fi


Block "setup a custom tmpfs dir at $aaa_tmpfs_location"
Info "the size can be configured in aaa-master-config"
Info "if your short of memory quit now"
MenuActive "q" "to quit"
MenuActive "any other key" "to continue and setup tmpfs on $aaa_tmpfs_location"
read -s -n1 aaa_tmpchr
if [[ $aaa_tmpchr == q ]]; then
	SaveSettings "aaa_tmpfs_exists_yes_no" "no"
	exit 0
else
	if [[ ! $(grep 'tmpfs' "/etc/fstab" | grep aaa) ]]; then
		Info "no aaa tmpfs system found doing the fs tab"
		MakeADir "$aaa_tmpfs_location"
		echo "#entry by aaa" >> /etc/fstab
		echo "tmpfs 			$aaa_tmpfs_location 	tmpfs 	rw,auto,dev,suid,exec,noatime,size=$aaa_tmpfs_size	 0		 0" >> /etc/fstab || Fuck "failed to write tmpfs fstab entrty "
		Info "fstab entry written you will need to"
		Info "reboot for changes to be active"
		Info "close all open windows"
		Info "if you want to reeboot yourself ${aaa_ctrl_c} to quit now"
		SaveSettings "aaa_tmpfs_exists_yes_no" "yes"
		aaa_reboot=yes
		AnyKey
	else
		if [[ $(cat "/etc/fstab" | grep "tmpfs 			$aaa_tmpfs_location 	tmpfs 	rw,auto,dev,suid,exec,noatime,size=$aaa_tmpfs_size	 0		 0") ]]; then
			Info "my entry for aaa tmpfs already exist"
			Info "it is exatly the entry i would write hence"
			Info "no further action necessary, but i would advise a reeboot anyway"
			SaveSettings "aaa_tmpfs_exists_yes_no" "yes"
			exit 0
		fi
		Warn "an old entry for aaa tmpfs already exist"
		Warn "i need to replace it since it seems "
		Warn "to have a different base location ie $aaa_tmpfs_location"
		MenuActive "n" "to leave existing aaa tmpfs entry and disable aaa tmpfs"
		MenuActive "any other key" "to replace"
		read -s -n1 aaa_tmpchr
		if [[ ! $aaa_tmpchr == n ]]; then
			sed -i 's/.*aaa.*//g' /etc/fstab
			MakeADir "$aaa_tmpfs_location"
			echo "#entry by aaa" >> /etc/fstab
			echo "tmpfs 			$aaa_tmpfs_location 	tmpfs 	rw,auto,dev,suid,exec,noatime,size=$aaa_tmpfs_size	 0		 0" >> /etc/fstab || Fuck "failed to write tmpfs fstab entrty "
			Warn "fstab entry rewritten you will need to"
			Warn "reboot for changes to be active"
			Warn "please remove the old aaa tmpfs folder after reboot"
			Warn "close all open windows"
			Warn "if you want to reeboot yourself ${aaa_ctrl_c} to quit now"
			SaveSettings "aaa_tmpfs_exists_yes_no" "yes"
			aaa_reboot=yes
			AnyKey
		else
					
			SaveSettings "aaa_tmpfs_exists_yes_no" "no"
		fi
	fi
fi

[[ $aaa_reboot == yes ]] && shutdown -r now
