#!/bin/bash


#source common functions
. /usr/bin/aaa-common-functions
 
for installed_pkg in $(dpkg-query -W | grep -v "kali" | awk '{print $1; }'); do
#	echo "$installed_pkg"
	axe_info "checking package $installed_pkg"
	if [[ ! -z $(apt-cache madison "$installed_pkg" | sed 's/http:\/\/http.kali.org\/kali\/ kali//' | sed 's/http:\/\/security.kali.org\/kali-security\/ kali//' | grep "kali") ]]; then
		found_one=$(apt-cache madison "$installed_pkg" | sed 's/http:\/\/http.kali.org\/kali\/ kali//' | sed 's/http:\/\/security.kali.org\/kali-security\/ kali//' | grep "kali")
		axe_fuck "the package $installed_pkg is present in the kali repos as a kali version"
		axe_fuck "but in your system the version is not the kali one"
		while [[ ! $quit_char == "q" ]]; do
			axe_fuck "$found_one"
			axe_menu_active "v" "run apt-cache madison $installed_pkg"
			axe_menu_active "a" "run aptitude versions $installed_pkg"
			axe_menu_active "r" "run aptitude"
			axe_menu_active "any other key" "to continue finding"
			read -s -n1 _AXE_TMP_CHAR
			case "$_AXE_TMP_CHAR" in
				v|V) vdetail=$(apt-cache madison "$installed_pkg")
					axe_info "$vdetail" ;;
				a|A) adetail=$(aptitude versions $installed_pkg)
					axe_info "$adetail" ;;
				r|R) aptitude ;;
				*) quit_char="q" ;;
			esac
		done
	fi
done
