#!/bin/bash


# master config file for AAA scripts ( debian )


# configs for all aaa scripts


############################## tmpfs environment #######################
#!!!!!!changing these values requires running !!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!aaa-setup-tmpfs AND!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!aaa-setup-build-env!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#########################################
#build in custom ramdisk or build on hdd
enable_tmpfs=yes
#enable_tmpfs=no
#########################################

###########################################
#location of tmpfs dir MUST START WITH aaa
aaa_tmpfs_location="/aaa-tmpfs"
###########################################

##########################################################
#max size of aaa tmpfs dir usually ram+swap, in gigs ie g
aaa_tmpfs_size=10g
##########################################################

####################### options activated if tmpfs=no###################
####################### if tmpfs=yes intrnal paths are used#############

##########################################################
#location of build results hdd
aaa_build_result_hdd="/var/cache/aaa/result"
#########################################################

##########################################################
#aaa_hdd_build_location hdd
aaa_hdd_build_location="/var/cache/aaa/build"
##########################################################

##########################################################
#location of my work dir - hdd 
aaa_work_dir_hdd="/var/cache/aaa/aaa-work-dir"
##########################################################


############################## pbuilder environment ####################
#!!!!!!changing these values requires running !!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!aaa-setup-build-env!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

##########################################################
#location for patches applid to builds
aaa_patch_dir="/usr/share/aaa/patches"
##########################################################

####################################################
#pbuilder hook dir
aaa_pbuilder_hookdir="/usr/share/aaa/pbuilder/hooks"
####################################################

######################################
#dir to keep base distro immage gz
aaa_base_gz_dir="/var/cache/pbuilder"
######################################

######################################################
aaa_debian_distro="testing"
#aaa_debian_distro="unstable"
#aaa_debian_distro="kali"
######################################################

########################################################
#architecture if specified will build for that arch ...
# only for advanced cross compiling
#architecture=
########################################################

#####################################################
#key to sign packages ( leave blank for no signing )
#aaa_sign_key="F3C33A59"
#####################################################


########################################################################
#maintainer string, must match local gpg key for
#signing NOT OPTIONAL !!!
aaa_maintainer="Jubei-Mitsuyoshi <jubei.house.of.five.masters@gmail.com>"

aaa_full_name="Jubei-Mitsuyoshi"
aaa_tag_name=""
aaa_maintainers_email="jubei.house.of.five.masters@gmail.com"
########################################################################

####################################
#extra build opts
aaa_extra_build_opts="-sa -us -uc"
####################################

##########################################################
#local repos, 
aaa_extra_repos="testing unstable saucy kali"
aaa_work_repo="work"
##########################################################

##########################################################

###############################
#
#space delimited list
aaa_extra_packages="apt-utils"
###############################

########################################################################
# on top of the default aaa_localrepo_dir
#space delimited list
aaa_extra_bindmounts=""
########################################################################




####################### mirrors ########################################
##################################################
#debian mirror
aaa_deb_mirror="ftp://ftp.dk.debian.org/debian/"
##################################################

##################################################
#kali mirror
aaa_kali_mirror="http://http.kali.org/kali/"
##################################################

##################################################
#ubuntu mirror
aaa_ubuntu_mirror="http://mirrors.telianet.dk/ubuntu-releases/"
##################################################
#################### end of mirrors ####################################




####################### keyrings #######################################
#################################################################
#debian keyring
aaa_deb_keyring="/usr/share/keyrings/debian-archive-keyring.gpg"
#################################################################

#################################################################
#kali keyring
aaa_kali_keyring="/usr/share/keyrings/kali-archive-keyring.gpg"
#################################################################

##################################################################
#ubuntu keyring
aaa_ubuntu_keyring="/usr/share/keyrings/ubuntu-archive-keyring.gpg"
###################################################################
####################### end of keyrings ################################




############################## reprepro environment ####################
#!!!!!!changing these values requires running !!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!aaa-setup-build-env!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

###############################
#base repo dir
aaa_localrepo_dir="/aaa-repo"
###############################

###############################
#new tag to identify packages
aaa_pkg_tag_testing="jessie"
aaa_pkg_tag_unstable="sid"
aaa_pkg_tag_kali="kali"
aaa_pkg_tag_ubuntu="saucy"
###############################



############################## aaa-build-cinnamon-pbuilder ##################################

##########################################################
#locatin for cinnamon git download
cinnamon_git_dir="$HOME/cinnamon-git"
##########################################################

##########################################################
#locatin for built package cache
aaa_cinnamon_cache_dir="$HOME/git/github/KALI-JESSIE/cinnamon-git-built"
##########################################################

##########################################################
#list of cinnamon git repos, order is very important and must be preserved
#note cinnamon is listed in lowere case wheras the actual git name is Cinnamon
#this is deliberate !
aaa_cinnamon_git_list="cinnamon-translations cinnamon-desktop cjs nemo cinnamon-settings-daemon cinnamon-session muffin cinnamon-control-center Cinnamon cinnamon-bluetooth cinnamon-screensaver cinnamon-themes nemo-extensions"
##########################################################



############################## aaa-build-compiz-emerald ##################################

##########################################################
#locatin for built package cache
aaa_compiz_cache_dir="$HOME/git/github/KALI-JESSIE/compiz-built"
##########################################################



############################## sort out final vars to pass ##################################

#add default work repo for pbuilder
aaa_extra_repos="$aaa_extra_repos $aaa_work_repo"

#RESPOND TO ENVIROMENTAL VARS	
case "$AAA_DEBIAN_DISTRO" in
	kali) aaa_debian_distro="kali" 
		echo "AAA_MASTER_CONFIG--->Responding to environmental variable AAA_DEBIAN_DISTRO=$AAA_DEBIAN_DISTRO" ;;
	testing) aaa_debian_distro="testing"  
		echo "AAA_MASTER_CONFIG--->Responding to environmental variable AAA_DEBIAN_DISTRO=$AAA_DEBIAN_DISTRO" ;;
	 stable) aaa_debian_distro="stable" 
		echo "AAA_MASTER_CONFIG--->Responding to environmental variable AAA_DEBIAN_DISTRO=$AAA_DEBIAN_DISTRO" ;;
   unstable) aaa_debian_distro="unstable" 
		echo "AAA_MASTER_CONFIG--->Responding to environmental variable AAA_DEBIAN_DISTRO=$AAA_DEBIAN_DISTRO" ;;
	 ubuntu) aaa_debian_distro="ubuntu" 
		echo "AAA_MASTER_CONFIG--->Responding to environmental variable AAA_DEBIAN_DISTRO=$AAA_DEBIAN_DISTRO" ;;
esac



case "$aaa_debian_distro" in

	kali) aaa_mirror="$aaa_kali_mirror" 
		aaa_pkg_tag="$aaa_pkg_tag_kali"
		aaa_base_components="main contrib non-free" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_kali_keyring' '--include=kali-archive-keyring')" ;;
	testing) aaa_mirror="$aaa_deb_mirror" 
		aaa_pkg_tag="$aaa_pkg_tag_testing"
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_deb_keyring')" 
		aaa_base_components="main contrib non-free" ;;
	stable) aaa_mirror="$aaa_deb_mirror" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_deb_keyring')" 
		aaa_pkg_tag="$aaa_pkg_tag_stable"
		aaa_base_components="main contrib non-free" ;;
	unstable) aaa_mirror="$aaa_deb_mirror" 
		aaa_pkg_tag="$aaa_pkg_tag_unstable"
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_deb_keyring')"
		aaa_base_components="main contrib non-free" ;;
	ubuntu) aaa_mirror="$aaa_ubuntu_mirror" 
		aaa_pkg_tag="$aaa_pkg_tag_ubuntu"
		aaa_extra_packages="$aaa_extra_packages ubuntu-archive-keyring" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_ubuntu_keyring' '--include=ubuntu-archive-keyring')"
		aaa_base_components="main restricted universe multiverse" ;;
esac


case "$enable_tmpfs" in
	yes) aaa_work_dir="$aaa_tmpfs_location/aaa-work-dir"
		aaa_build_location="$aaa_tmpfs_location/aaa-build"
		aaa_build_result="$aaa_tmpfs_location/aaa-build-result"
		aaa_hardlink="no" ;;
	no) aaa_work_dir="$aaa_work_dir_hdd"
		aaa_build_result="$aaa_build_result_hdd"
		aaa_build_location="$aaa_hdd_build_location"
		aaa_hardlink="yes" ;;
esac

aaa_cores=$((    $(cat /proc/cpuinfo | grep processor | wc -l)+1    ))

if [[ -z "${architecture}" ]]; then	
	aaa_buildopts="$aaa_extra_build_opts -j$aaa_cores"
	aaa_base_gz="$aaa_debian_distro-base.tgz"
else
	aaa_buildopts="--arch $architecture $aaa_extra_build_opts -j$aaa_cores"
	aaa_base_gz="$aaa_debian_distro-$architecture-base.tgz"
fi


aaa_tmp=""
bind_target_space=""
for bind_target in $aaa_extra_bindmounts; do
	bind_target_space=" $bind_target"
	aaa_tmp=("$aaa_tmp""$bind_target_space")
done
aaa_bindmounts=("$aaa_localrepo_dir""$aaa_tmp")
#possible extra debootstrapopt
# -m$aaa_maintainer


if [[ ! "$AAA_SUPRESS_LOCAL_PBUILDERRC" == "yes" ]]; then
	echo "MIRRORSITE=\"$aaa_mirror\"
OTHERMIRROR=\"deb [trusted=yes] file://$aaa_localrepo_dir $aaa_work_repo main\"
BINDMOUNTS=\"$aaa_bindmounts\"
HOOKDIR=\"$aaa_pbuilder_hookdir\"
EXTRAPACKAGES=\"$aaa_extra_packages\"

DEBEMAIL=\"$aaa_maintainer\"
BUILDRESULT=\"$aaa_build_result\"
COMPONENTS=\"$aaa_base_components\"
DEBBUILDOPTS=\"$aaa_buildopts\"
DEBOOTSTRAPOPTS=$aaa_debootstrap_opts
BUILDUSERNAME=\"\"
AUTO_DEBSIGN=no
DISTRIBUTION=$aaa_debian_distro
APTCACHEHARDLINK=$aaa_hardlink
BASETGZ=\"$aaa_base_gz_dir/$aaa_base_gz\"
BUILDPLACE=\"$aaa_build_location\"" > "$HOME/.pbuilderrc"

fi
