#!/bin/bash

shopt -s extglob

cd "$HOME"

Usage() {
  cat <<EOF
usage: ${0##*/}
 this little script sets up cinnamon
 after it has been built with
 aaa-build-cinnamon-
 

EOF
}

if [[ $1 = @(-h|--help) ]]; then
  Usage
  exit 1
fi

#source common functions
if [[ -r /usr/bin/aaa-common-functions ]]; then
	. /usr/bin/aaa-common-functions
	if [[ ! $? -eq 0 ]]; then
		echo " failed to source common functions at /usr/bin/aaa-common-functions"
		echo "quitting !! "
		exit 1
	fi
else
	echo " failed to find common functions at /usr/bin/aaa-common-functions"
	echo "quitting !! "
	exit 1
fi

#check script dependencies
CheckMyDeps "apt"


apt-get update
#apt-get dist-upgrade
/etc/init.d/gdm3 stop > /dev/null 2>&1
apt-get --no-upgrade --no-install-recommends install xinit
apt-get --no-upgrade purge gdm3
apt-get --no-upgrade purge "gnome-settings-daemon*"
apt-get --no-upgrade purge "gnome-session*"
apt-get --no-upgrade --no-install-recommends  install "cinnamon*" "muffin*" "cjs*" "nemo*"

Info "chose muffin here in the next dialog"
update-alternatives --config x-window-manager

Info "chose cinnamon-session in the next dialog"
update-alternatives --config x-session-manager


Info "now type startx"
