#!/bin/bash


shopt -s extglob

cd "$HOME"

#source common functions
. /usr/bin/aaa-common-functions

#source settings
if [ -r $HOME/.aaa_settings ]; then
  Info "found a settings file.. reading it"
  . $HOME/.aaa_settings
fi

#source config
if [ -r /usr/share/aaa/aaa-master-config ]; then
  Info "found my master config file.. reading it"
  . /usr/share/aaa/aaa-master-config
	if [ -r $HOME/.aaa-local-config ]; then
		Info "found a local settings file.. reading it"
		. $HOME/.aaa-local-config
	fi
else
	Fuck "Failed to find master settings file quitting"
	exit 1
fi


#check script dependencies

CheckMyDeps "changestool pbuilder"

[[ $aaa_build_env_setup_complete_yes_no == "yes" ]] || Fuck "this script need the build environment setup, run aaa-setup-build-env"



###################### EMERALD ####################################################

CleanMyBuildArea


CleanMyRepo testing "emerald"

cd "$aaa_work_dir"


DownLoad "https://launchpad.net/~nilarimogard/+archive/webupd8/+files/emerald_0.9.5-0%7Ewebupd8%7Eraring2.debian.tar.gz"
DownLoad "https://launchpad.net/~nilarimogard/+archive/webupd8/+files/emerald_0.9.5-0%7Ewebupd8%7Eraring2.dsc"
DownLoad "https://launchpad.net/~nilarimogard/+archive/webupd8/+files/emerald_0.9.5.orig.tar.gz"


dpkg-source -x --skip-patches emerald_0.9.5-0~webupd8~raring2.dsc

rm -f * >/dev/null 2>&1
cd emerald-0.9.5
 
 #change deps, change format
 
sed -i 's/compiz-dev (>= 1:0.7.2),/compizconfig-settings-manager, libwnck1.0-cil-dev,/' "./debian/control"

sed -i 's/quilt/native/' "./debian/source/format"

#stamp pkg
ModDEbFiles

cd .. && dpkg-source -b emerald-0.9.5

pbuilder --build emerald_0.9.5-jessiekali.dsc || Fuck "something wrong with pdebuild check the output"

cd "$aaa_build_result"


reprepro -b "$aaa_localrepo_dir" include testing emerald_0.9.5-jessiekali_amd64.changes || Fuck "something wrong with-- reprepro -b $aaa_localrepo_dir include testing *.changes ---check the output"


cd $HOME
rm -rf "$aaa_work_dir/emerald-build"

cd $HOME
rm -rf "$aaa_work_dir"
rm -rf "$aaa_build_location"
rm -rf "$aaa_build_result"












#wget cgit.compiz.org/fusion/decorators/emerald/snapshot/emerald-0.9.5.tar.gz
#tar -zxvf emerald-0.9.5.tar.gz
#cd emerald-0.9.5/
#./autogen.sh
#make clean
#make distclean
#auto-apt run ./configure --prefix=/usr --libdir=/usr/lib${LIBDIRSUFFIX} LIBS='-ldl -lm'
#make
#checkinstall --fstrans=yes make install

