#!/bin/bash

#aaa-checked



##### Configure aliases
#--- Enable defaults
#for file in $HOME/.bash_aliases $HOME/.bashrc /etc/bashrc /etc/bash.bashrc; do
#   if [ -e $file ]; then cp -n $file{,.bkup}; fi
#   touch $file
#   sed -i 's/#alias/alias/g' $file
#done
#--- Add in ours
grep -q '### tmux' $HOME/.bash_aliases || echo -e '\n### tmux\nalias tmux="tmux attach || tmux new"\n' >> $HOME/.bash_aliases
grep -q '### axel' $HOME/.bash_aliases || echo -e '\n### axel\nalias axel="axel -a"\n' >> $HOME/.bash_aliases
grep -q '### screen' $HOME/.bash_aliases || echo -e '\n### screen\nalias screen="screen -xRR"\n' >> $HOME/.bash_aliases
grep -q '### Directory navigation aliases' $HOME/.bash_aliases || echo -e '\n### Directory navigation aliases\nalias ..="cd .."\nalias ...="cd ../.."\nalias ....="cd ../../.."\nalias .....="cd ../../../.."\n\n' >> $HOME/.bash_aliases
grep -q '### Extract file, example' $HOME/.bash_aliases || echo -e '\n### Extract file, example. "ex package.tar.bz2"\nex() {\n    if [[ -f $1 ]]; then\n        case $1 in\n            *.tar.bz2)   tar xjf $1  ;;\n            *.tar.gz)    tar xzf $1  ;;\n            *.bz2)       bunzip2 $1  ;;\n            *.rar)       rar x $1    ;;\n            *.gz)        gunzip $1   ;;\n            *.tar)       tar xf $1   ;;\n            *.tbz2)      tar xjf $1  ;;\n            *.tgz)       tar xzf $1  ;;\n            *.zip)       unzip $1    ;;\n            *.Z)         uncompress $1  ;;\n            *.7z)        7z x $1     ;;\n            *)           echo $1 cannot be extracted ;;\n        esac\n    else\n        echo $1 is not a valid file\n    fi\n}' >> $HOME/.bash_aliases
#--- Apply new aliases
source $HOME/.bash_aliases     #source /root/.bashrc    # If using ZSH, will fail
#--- Check
#alias

