#!/bin/bash

Usage() {
  cat <<EOF
usage: ${0##*/} [options]

  -c | --clean remove all symlinks,restore
  backups
  
  

EOF
}

if [[ $1 = @(-h|--help) ]]; then
  Usage
  exit 1
fi

while getopts 'c' arg; do
	case "$arg" in
		c|--clean) clean_up=1 ;;
	esac
done


function MakeADir()
{
	
	
	if [[ ! -d "$1" ]]; then
			mkdir -p "$1" || exit 2
	fi
	
	
}

conf_path="/etc/aaa"
bin_path="/usr/bin"


hook_path="$conf_path/pbuilder/hooks"
patch_path="$conf_path/patches"


binlinks="aaa-common-functions \
aaa-setup-build-env \
aaa-setup-build-base"
	
hooklinks="D05deps A10change_distro.sh"

etclinks="aaa-master-config"

for f in $binlinks; do 
	[[ $clean_up ]] && rm -f "$bin_path/$f"
	[[ $clean_up ]] || ln -s -f "$(pwd)/$f" "$bin_path/$f"
done

MakeADir "$conf_path/patches"
MakeADir "$conf_path/pbuilder/hooks"
	
for file in `find . -maxdepth 1 -mindepth 1 -type f -name "*.patch"`; do 
	[[ $clean_up ]] && rm -f "$patch_path/${file#./}"
	[[ $clean_up ]] || ln -s -f "$(pwd)/${file#./}" "$patch_path/${file#./}"
done	
 
for f in $hooklinks; do 
	[[ $clean_up ]] && rm -f "$hook_path/$f"
	[[ $clean_up ]] || ln -s -f "$(pwd)/$f" "$hook_path/$f"
done

for f in $etclinks; do 
	[[ $clean_up ]] && rm -f "/etc/$f"
	[[ $clean_up ]] || ln -s -f "$(pwd)/$f" "/etc/$f"
done

for patch_dir in `find . -maxdepth 1 -mindepth 1 -type d`; do 
	MakeADir "$patch_path/${patch_dir%%/}"
	[[ $clean_up ]] && rm -fr "$patch_path/${patch_dir%%/}"
	if [[ ! $clean_up ]]; then
		cd "${patch_dir%%/}"
		for conf_file in `find . -maxdepth 1 -mindepth 1 -type f`; do
			ln -s -f "$(pwd)/${conf_file#./}" "$patch_path/${patch_dir%%/}/${conf_file#./}"
		done
		cd ..
	fi
done
