#!/bin/bash


# master config file for AAA scripts ( debian )


# configs for all aaa scripts


############################## tmpfs environment #######################
#!!!!!!changing these values requires running !!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!aaa-setup-build-base AND!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!aaa-setup-build-env!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#########################################
#build in custom ramdisk or build on hdd
#if you change this after running aaa-setup-build-base
#you need to run aaa-setup-build-base again
enable_tmpfs=yes
#enable_tmpfs=no
#########################################

###########################################
#location of tmpfs dir MUST START WITH aaa
#if you change this after running aaa-setup-build-base
#you need to run aaa-setup-build-base again
aaa_tmpfs_location="/aaa-tmpfs"
###########################################

##########################################################
#max size of aaa tmpfs dir usually ram+swap, in gigs ie g
#do not worry if the value is above you physical ram, if short of ram
#tmpfs will use the swap disk instead
#if you change this after running aaa-setup-build-base
#you need to run aaa-setup-build-base again
aaa_tmpfs_size=10g
##########################################################

####################### options activated if tmpfs=no###################
####################### if tmpfs=yes intrnal paths are used#############

##########################################################
#location of build results hdd
#if you change this after running aaa-setup-build-base
#you need to run aaa-setup-build-base again
aaa_build_result_hdd="/var/cache/aaa/result"
#########################################################

##########################################################
#aaa_hdd_build_location hdd
#if you change this after running aaa-setup-build-base
#you need to run aaa-setup-build-base again
aaa_hdd_build_location="/var/cache/aaa/build"
##########################################################

##########################################################
#location of my work dir - hdd
#if you change this after running aaa-setup-build-base
#you need to run aaa-setup-build-base again
aaa_work_dir_hdd="/var/cache/aaa/aaa-work-dir"
##########################################################


############################## pbuilder environment ####################
#!!!!!!changing these values requires running !!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!aaa-setup-build-env!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

##########################################################
#location for patches applid to builds
#WARNING ABSOLUTE PATHS IN MAKEFILES AND LINK SCRIPTS
aaa_patch_dir="/etc/aaa/patches"
##########################################################

####################################################
#pbuilder hook dir
#WARNING HARD PATHS IN MAKEFILES AND LINK SCRIPTS
aaa_pbuilder_hookdir="/etc/aaa/pbuilder/hooks"
####################################################

####################################################
#pbuilder base apt-cache dir, subdires for each distro will be used
#wastes a lot of hdd space but essential for multi distro
aaa_apt_cache_base_dir="/var/cache/pbuilder/aptcache"
####################################################

######################################
#dir to keep base distro immage gz
aaa_base_gz_dir="/var/cache/pbuilder"
######################################

######################################################
#aaa_debian_distro="testing"
aaa_debian_distro="unstable"
#aaa_debian_distro="kali"
######################################################

########################################################
#architecture if specified will build for that arch ...
# only for advanced cross compiling
#architecture=
########################################################

#####################################################
#key to sign packages ( leave blank for no signing )
#aaa_sign_key="F3C33A59"
#####################################################


########################################################################
#maintainer string, must match local gpg key for
#signing NOT OPTIONAL !!!
aaa_maintainer="Jubei Mitsuyoshi <jubei.house.of.five.masters@gmail.com>"

########################################################################

####################################
#extra build opts
aaa_extra_build_opts="-sa -us -uc"
####################################

##########################################################
#local repos, 
aaa_extra_repos="testing unstable saucy kali"
aaa_work_repo="work"
##########################################################

##########################################################

###############################
#
#space delimited list
aaa_extra_packages="apt-utils devscripts lsb-release"
###############################

########################################################################
# on top of the default aaa_localrepo_dir
#space delimited list
aaa_extra_bindmounts=""
########################################################################




####################### mirrors ########################################
##################################################
#debian mirror
aaa_deb_mirror="ftp://ftp.dk.debian.org/debian/"
##################################################

##################################################
#kali mirror
aaa_kali_mirror="http://http.kali.org/kali/"
##################################################

##################################################
#ubuntu mirror
aaa_ubuntu_mirror="http://mirrors.telianet.dk/ubuntu-releases/"
##################################################
#################### end of mirrors ####################################




####################### keyrings #######################################
#################################################################
#debian keyring
aaa_deb_keyring="/usr/share/keyrings/debian-archive-keyring.gpg"
#################################################################

#################################################################
#kali keyring
aaa_kali_keyring="/usr/share/keyrings/kali-archive-keyring.gpg"
#################################################################

##################################################################
#ubuntu keyring
aaa_ubuntu_keyring="/usr/share/keyrings/ubuntu-archive-keyring.gpg"
###################################################################
####################### end of keyrings ################################




############################## reprepro environment ####################
#!!!!!!changing these values requires running !!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!aaa-setup-build-env!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

###############################
#base repo dir
aaa_localrepo_dir="/aaa-repo"
###############################

###############################
#mirror repo dir, used if in kind mode
#just leave unset to disable kind mode
aaa_git_repo_dir="$HOME/git/github/aaa-debian-repo"
##############################

###############################
#new tag to identify packages
aaa_pkg_tag_testing="aaajessie"
aaa_pkg_tag_unstable="aaasid"
aaa_pkg_tag_kali="aaakali"
aaa_pkg_tag_ubuntu="aaasaucy"
###############################



############################## aaa-build-cinnamon ##################################

##########################################################
#locatin for cinnamon releases download and storage
aaa_cinnamon_sources_release="$HOME/cinnamon-releases"
##########################################################

##########################################################
#locatin for cinnamon releases download and storage
aaa_cinnamon_sources_git="$HOME/cinnamon-git"
##########################################################

##########################################################
#mint git url
aaa_mint_git_url="git://github.com/linuxmint"
##########################################################

##########################################################
#list of cinnamon packages that must be built from git since
#there are no git releases, or you can chose to build a git
#package instead of a relese version in which case you would
#MOVE the package name from release list to git list
#as usual order is important
aaa_cinnamon_git_list="cinnamon-themes nemo-extensions"
##########################################################

##########################################################
#list of cinnamon release packages, order is very important and must be preserved
#note cinnamon is listed in lowere case wheras the actual git name is Cinnamon
#this is deliberate !
aaa_cinnamon_release_list="cinnamon-translations cinnamon-desktop cjs nemo cinnamon-settings-daemon cinnamon-session muffin cinnamon-control-center Cinnamon cinnamon-bluetooth cinnamon-screensaver"
##########################################################




############################## aaa-build-compiz-emerald ##################################


##########################################################
#jubei git url
aaa_jubei_git_url="git://github.com/Jubei-Mitsuyoshi"
##########################################################

############################## aaa-build-pupvm ##################################



############################## sort out final vars to pass --do not mod this unless you know what your doing--##################################

#add default work repo for pbuilder
aaa_extra_repos="$aaa_extra_repos $aaa_work_repo"


case "$aaa_debian_distro" in

	kali) aaa_mirror="$aaa_kali_mirror" 
		aaa_pkg_tag="$aaa_pkg_tag_kali"
		aaa_base_components="main contrib non-free" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_kali_keyring' '--include=kali-archive-keyring')" ;;
	testing) aaa_mirror="$aaa_deb_mirror" 
		aaa_pkg_tag="$aaa_pkg_tag_testing"
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_deb_keyring')" 
		aaa_base_components="main contrib non-free" ;;
	stable) aaa_mirror="$aaa_deb_mirror" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_deb_keyring')" 
		aaa_pkg_tag="$aaa_pkg_tag_stable"
		aaa_base_components="main contrib non-free" ;;
	unstable) aaa_mirror="$aaa_deb_mirror" 
		aaa_pkg_tag="$aaa_pkg_tag_unstable"
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_deb_keyring')"
		aaa_base_components="main contrib non-free" ;;
	ubuntu) aaa_mirror="$aaa_ubuntu_mirror" 
		aaa_pkg_tag="$aaa_pkg_tag_ubuntu"
		aaa_extra_packages="$aaa_extra_packages ubuntu-archive-keyring" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_ubuntu_keyring' '--include=ubuntu-archive-keyring')"
		aaa_base_components="main restricted universe multiverse" ;;
esac


case "$enable_tmpfs" in
	yes) aaa_work_dir="$aaa_tmpfs_location/aaa-work-dir"
		aaa_build_location="$aaa_tmpfs_location/aaa-build"
		aaa_build_result="$aaa_tmpfs_location/aaa-build-result"
		aaa_hardlink="no" ;;
	no) aaa_work_dir="$aaa_work_dir_hdd"
		aaa_build_result="$aaa_build_result_hdd"
		aaa_build_location="$aaa_hdd_build_location"
		aaa_hardlink="yes";;
esac

aaa_cores=$((    $(cat /proc/cpuinfo | grep processor | wc -l)+1    ))

if [[ -z "${architecture}" ]]; then	
	aaa_buildopts="$aaa_extra_build_opts -j$aaa_cores"
	aaa_base_gz="$aaa_debian_distro-base.tgz"
else
	aaa_buildopts="--arch $architecture $aaa_extra_build_opts -j$aaa_cores"
	aaa_base_gz="$aaa_debian_distro-$architecture-base.tgz"
fi


aaa_tmp=""
bind_target_space=""
for bind_target in $aaa_extra_bindmounts; do
	bind_target_space=" $bind_target"
	aaa_tmp=("$aaa_tmp""$bind_target_space")
done
aaa_bindmounts=("$aaa_localrepo_dir""$aaa_tmp")
#possible extra debootstrapopt
# -m$aaa_maintainer



export AAA_HOST_ARCH=${ARCH:="$(dpkg --print-architecture)"}
export DEBEMAIL="$aaa_maintainer"
export DEBFULLNAME="${aaa_maintainer% <*}"

aaa_apt_cache_dir="$aaa_apt_cache_base_dir/$aaa_debian_distro"


