#!/bin/sh -e
# $Id: sv-checkdeps,v 1.10 2005/02/24 03:55:07 dean Exp $
#
#    Author: Dean Hall <dean.hall@gmail.com>
# Copyright: (c) 2005, Dean Hall
#   License: BSD (see COPYING)
#
# sv-checkdeps checks dependencies in the directory
# specified by the environment variable SV_DEPS_DIR, or
# if SV_DEPS_DIR is zero-length, ./deps. Each (symlink to
# a) directory and (symlink to an) executable file in the
# directory, except those whose names start with a dot, is
# considered a dependency.
#
# For each dependency, sv-checkdeps runs sv-require with
# the path to the dependency as the only argument. If the
# environment variable SV_REQUIRE_ENVDIR is non-zero-length,
# sv-checkdeps will run sv-require with the environment
# from that envdir (gathered by the current user). If the
# environment variable SV_DEPS_USER is non-zero-length,
# sv-checkdeps will run sv-require as the user specified in
# SV_DEPS_USER.
# 
# NOTE: The user is responsible for making sure that the
# dependency directory is not writable by unauthorized
# users and that dependencies both are accessible to the
# running user and run as expected.
#
PATH='/usr/sbin:/usr/bin:/sbin:/bin'

die()
{
	echo "sv-checkdeps: $*" 1>&2
	exit 111
}

check_dir()
{
	dir="$1"
	if test ! -e "$dir" ; then
		die "Directory '$dir' does not exist."
	elif test ! -d "$dir" ; then
		die "File '$dir' is not a directory."
	fi
}

if test -z "$SV_DEPS_DIR" ; then
	SV_DEPS_DIR='./deps'
fi

check_dir "$SV_DEPS_DIR"
cd "$SV_DEPS_DIR"

if test -e * ; then
	if test -n "$SV_REQUIRE_ENVDIR" ; then
		check_dir "$SV_REQUIRE_ENVDIR"
		base_command="envdir '$SV_REQUIRE_ENVDIR'"
	fi
	if test -n "$SV_DEPS_USER" ; then
		base_command="${base_command} setuidgid '$SV_DEPS_USER'"
	fi
	base_command="${base_command} sv-require"

	for dep in * ; do
		$base_command "$dep"
	done
fi
