#!/bin/sh -e
# $Id: sv-require,v 1.8 2005/02/24 03:55:07 dean Exp $
#
#    Author: Dean Hall <dean.hall@gmail.com>
# Copyright: (c) 2005, Dean Hall
#   License: BSD (see COPYING)
#
# sv-require checks an individual dependency; the
# dependency (arg $1) should be either a service directory
# or an executable. If it is neither, sv-require will exit
# successfully without doing any checks.
#
PATH='/usr/sbin:/usr/bin:/sbin:/bin'

# the dependency (a service directory or an executable file):
dep="$1"

# Test usage.
if test -z "$dep" ; then
	echo "Usage: `basename $0` <svdir|executable>" 1>&2
	exit 100
fi

# Dependency is a directory; test its service.
if test -d "$dep" ; then
	# Assert that the service is running.
	sv-isrunning "$dep"
# Dependency is an executable; run it.
elif test -x "$dep" ; then
	# Assert that the executable is successful.
	$dep
fi
