#!/bin/sh -e
# $Id: sv-runlock,v 1.6 2005/02/24 03:55:07 dean Exp $
# 
#    Author: Dean Hall <dean.hall@gmail.com>
# Copyright: (c) 2005, Dean Hall
#   License: BSD (see COPYING)
#
# sv-runlock locks the file specified in the environment
# variable SV_LOCKFILE if it non-zero-length or ./sv-lock,
# and then it runs its arguments. If the environment
# variable SV_INVERSE is set to '1', it asserts that the
# file is already locked (and discards its arguments).
#
# sv-runlock uses the environment variable SV_BIN_FALSE as
# the executable to run to return a non-zero value or
# /bin/false if SV_BIN_FALSE is zero-length.
#
PATH='/usr/sbin:/usr/bin:/sbin:/bin'

if test -z "$SV_LOCKFILE" ; then
	SV_LOCKFILE='./sv-lock'
fi

# Assert that the file is locked.
if test "$SV_INVERSE" = '1' ; then
	if test -z "$SV_BIN_FALSE" ; then
		SV_BIN_FALSE='/bin/false'
	fi
	exec setlock -xn "$SV_LOCKFILE" "$SV_BIN_FALSE"
# Set the lock, and run the args.
else
	exec setlock -nX "$SV_LOCKFILE" $*
fi
